export default {
  years: [
      { id: 2021, name: '2021' },
      { id: 2022, name: '2022' },
      { id: 2023, name: '2023' },
      { id: 2024, name: '2024' },
      { id: 2025, name: '2025' }
  ],
  months: [
      { id: 1, name: 'January' },
      { id: 2, name: 'February' },
      { id: 3, name: 'March' },
      { id: 4, name: 'April' },
      { id: 5, name: 'May' },
      { id: 6, name: 'June' },
      { id: 7, name: 'July' },
      { id: 8, name: 'August' },
      { id: 9, name: 'September' },
      { id: 10, name: 'October' },
      { id: 11, name: 'November' },
      { id: 12, name: 'December' }
  ],

  travelers: [
    { id: 1, name: '1 adult'},
    { id: 2, name: '1 adult+1 kid' },
    { id: 3, name: '1 adult+2 kids' },
    { id: 4, name: '2 adults' },
    { id: 5, name: '2 adults+1 kid' },
    { id: 6, name: '2 adults+2 kids' }
  ],
	cities: [
		{id: 1, name: "Mauritius"},
		{id: 2, name: "Hawaii"},
		{id: 3, name: "Herat"},
		{id: 4, name: "Kabul"},
		{id: 5, name: "Mazar-e Sharif"},
		{id: 6, name: "Korce"},
		{id: 7, name: "Tirane"},
		{id: 8, name: "Algiers"},
		{id: 9, name: "Skikda"},
		{id: 10, name: "Oran"},
		{id: 11, name: "Ouled Djellal"},
		{id: 12, name: "Mascara"},
		{id: 13, name: "Annaba"},
		{id: 14, name: "Pago Pago"},
		{id: 15, name: "Andorra La Vella"},
		{id: 16, name: "Escaldes"},
		{id: 17, name: "Benguela"},
		{id: 18, name: "Sumbe"},
		{id: 19, name: "Lubango"},
		{id: 20, name: "Luanda"},
		{id: 21, name: "The Valley"},
		{id: 22, name: "Molodesjnaja"},
		{id: 23, name: "Reading"},
		{id: 24, name: "McMurdo Station"},
		{id: 25, name: "Saint Johns"},
		{id: 26, name: "Falmouth"},
		{id: 27, name: "Bahia Blanca"},
		{id: 28, name: "Berazategui"},
		{id: 29, name: "Caseros"},
		{id: 30, name: "Castelar"},
		{id: 31, name: "Chacabuco"},
		{id: 32, name: "Ezeiza"},
		{id: 33, name: "Haedo"},
		{id: 34, name: "Jose Leon Suarez"},
		{id: 35, name: "La Plata"},
		{id: 36, name: "Lomas De Zamora"},
		{id: 37, name: "Mar del Plata"},
		{id: 38, name: "Miramar"},
		{id: 39, name: "Pinamar"},
		{id: 40, name: "Ramos Mejia"},
		{id: 41, name: "Salto"},
		{id: 42, name: "San Clemente del Tuyú"},
		{id: 43, name: "San Isidro"},
		{id: 44, name: "San Martin"},
		{id: 45, name: "Tres Arroyos"},
		{id: 46, name: "Turdera"},
		{id: 47, name: "Puerto Madryn"},
		{id: 48, name: "Trelew"},
		{id: 49, name: "Cordoba"},
		{id: 50, name: "Marcos Juárez"},
		{id: 51, name: "Rio Tercero"},
		{id: 52, name: "Villa María"},
		{id: 53, name: "Corrientes"},
		{id: 54, name: "Paso de los Libres"},
		{id: 55, name: "Buenos Aires"},
		{id: 56, name: "Concordia"},
		{id: 57, name: "Crespo"},
		{id: 58, name: "Gualeguaychu"},
		{id: 59, name: "Paraná"},
		{id: 60, name: "San Rafael"},
		{id: 61, name: "Santa Rosa"},
		{id: 62, name: "Luján de Cuyo"},
		{id: 63, name: "Malargüe"},
		{id: 64, name: "Mendoza"},
		{id: 65, name: "Cipolletti"},
		{id: 66, name: "Neuquen"},
		{id: 67, name: "Bariloche"},
		{id: 68, name: "General Roca"},
		{id: 69, name: "Resistencia"},
		{id: 70, name: "Salta"},
		{id: 71, name: "San Juan"},
		{id: 72, name: "Rio Cuarto"},
		{id: 73, name: "Ceres"},
		{id: 74, name: "Reconquista"},
		{id: 75, name: "Rosario"},
		{id: 76, name: "Santa Fe"},
		{id: 77, name: "Suardi"},
		{id: 78, name: "Santiago del Estero"},
		{id: 79, name: "Ushuaia"},
		{id: 80, name: "San Miguel de Tucuman"},
		{id: 81, name: "Vanadzor"},
		{id: 82, name: "Gyumri"},
		{id: 83, name: "Spitak"},
		{id: 84, name: "Yerevan"},
		{id: 85, name: "Oranjestad"},
		{id: 86, name: "Ascot Vale"},
		{id: 87, name: "Bacchus Marsh"},
		{id: 88, name: "Bairnsdale"},
		{id: 89, name: "Ballarat"},
		{id: 90, name: "Bayswater"},
		{id: 91, name: "Bendigo"},
		{id: 92, name: "Berwick"},
		{id: 93, name: "Boolarra"},
		{id: 94, name: "Bright"},
		{id: 95, name: "Cape Otway"},
		{id: 96, name: "Castlemaine"},
		{id: 97, name: "Chelsea"},
		{id: 98, name: "Cheltenham"},
		{id: 99, name: "Cobram"},
		{id: 100, name: "Dandenong"},
		{id: 101, name: "Deer Park"},
		{id: 102, name: "Diamond Creek"},
		{id: 103, name: "Echuca"},
		{id: 104, name: "Eltham"},
		{id: 105, name: "Frankston"},
		{id: 106, name: "Geelong"},
		{id: 107, name: "Hamilton"},
		{id: 108, name: "Hawthorn"},
		{id: 109, name: "Horsham"},
		{id: 110, name: "Hurstbridge"},
		{id: 111, name: "Maryborough"},
		{id: 112, name: "Melbourne"},
		{id: 113, name: "Mildura"},
		{id: 114, name: "Moe"},
		{id: 115, name: "Mooroolbark"},
		{id: 116, name: "Mornington"},
		{id: 117, name: "Morwell"},
		{id: 118, name: "Narre Warren"},
		{id: 119, name: "Newstead"},
		{id: 120, name: "Noble Park"},
		{id: 121, name: "Nunawading"},
		{id: 122, name: "Portland"},
		{id: 123, name: "Prahran"},
		{id: 124, name: "Preston"},
		{id: 125, name: "Red Cliffs"},
		{id: 126, name: "Sale"},
		{id: 127, name: "Shepparton"},
		{id: 128, name: "Sorrento"},
		{id: 129, name: "South Yarra"},
		{id: 130, name: "Sunbury"},
		{id: 131, name: "Sunshine"},
		{id: 132, name: "Swan Hill"},
		{id: 133, name: "Traralgon"},
		{id: 134, name: "Wangaratta"},
		{id: 135, name: "Warrnambool"},
		{id: 136, name: "Wilsons Promontory"},
		{id: 137, name: "Wodonga"},
		{id: 138, name: "Burnie"},
		{id: 139, name: "Campbell Town"},
		{id: 140, name: "Claremont"},
		{id: 141, name: "Devonport"},
		{id: 142, name: "George Town"},
		{id: 143, name: "Glenorchy"},
		{id: 144, name: "Hobart"},
		{id: 145, name: "Launceston"},
		{id: 146, name: "Penguin"},
		{id: 147, name: "Strahan"},
		{id: 148, name: "Wynyard"},
		{id: 149, name: "Zeehan"},
		{id: 150, name: "Birdsville"},
		{id: 151, name: "Blue Mountain"},
		{id: 152, name: "Boulia"},
		{id: 153, name: "Bowen"},
		{id: 154, name: "Brisbane"},
		{id: 155, name: "Bundaberg"},
		{id: 156, name: "Burpengary"},
		{id: 157, name: "Caboolture"},
		{id: 158, name: "Cairns"},
		{id: 159, name: "Caloundra"},
		{id: 160, name: "Charleville"},
		{id: 161, name: "Cooktown"},
		{id: 162, name: "Croydon"},
		{id: 163, name: "Cunnamulla"},
		{id: 164, name: "Emerald"},
		{id: 165, name: "Gladstone"},
		{id: 166, name: "Gold Coast"},
		{id: 167, name: "Goondiwindi"},
		{id: 168, name: "Gympie"},
		{id: 169, name: "Ingham"},
		{id: 170, name: "Ipswich"},
		{id: 171, name: "Kingaroy"},
		{id: 172, name: "Longreach"},
		{id: 173, name: "Mackay"},
		{id: 174, name: "Maleny"},
		{id: 175, name: "Manly"},
		{id: 176, name: "Maroochydore"},
		{id: 177, name: "Mount Isa"},
		{id: 178, name: "Nambour"},
		{id: 179, name: "Noosa"},
		{id: 180, name: "Redcliffe"},
		{id: 181, name: "Richmond"},
		{id: 182, name: "Rockhampton"},
		{id: 183, name: "Roma"},
		{id: 184, name: "Southport"},
		{id: 185, name: "Stanthorpe"},
		{id: 186, name: "Toowoomba"},
		{id: 187, name: "Torquay"},
		{id: 188, name: "Townsville"},
		{id: 189, name: "Windorah"},
		{id: 190, name: "Albury"},
		{id: 191, name: "Armidale"},
		{id: 192, name: "Ballina"},
		{id: 193, name: "Bankstown"},
		{id: 194, name: "Batemans Bay"},
		{id: 195, name: "Bathurst"},
		{id: 196, name: "Bega"},
		{id: 197, name: "Blacktown"},
		{id: 198, name: "Bombala"},
		{id: 199, name: "Bondi"},
		{id: 200, name: "Bourke"},
		{id: 201, name: "Bowral"},
		{id: 202, name: "Broken Hill"},
		{id: 203, name: "Burwood"},
		{id: 204, name: "Byron Bay"},
		{id: 205, name: "Camden"},
		{id: 206, name: "Campbelltown"},
		{id: 207, name: "Cessnock"},
		{id: 208, name: "Cobar"},
		{id: 209, name: "Coffs Harbour"},
		{id: 210, name: "Cooma"},
		{id: 211, name: "Cootamundra"},
		{id: 212, name: "Dubbo"},
		{id: 213, name: "Dural"},
		{id: 214, name: "Fairlight"},
		{id: 215, name: "Gosford"},
		{id: 216, name: "Goulburn"},
		{id: 217, name: "Grafton"},
		{id: 218, name: "Griffith"},
		{id: 219, name: "Hurstville"},
		{id: 220, name: "Inverell"},
		{id: 221, name: "Katoomba"},
		{id: 222, name: "Kempsey"},
		{id: 223, name: "Lake Haven"},
		{id: 224, name: "Lidcombe"},
		{id: 225, name: "Lightning Ridge"},
		{id: 226, name: "Lismore"},
		{id: 227, name: "Lithgow"},
		{id: 228, name: "Liverpool"},
		{id: 229, name: "Maitland"},
		{id: 230, name: "Mona Vale"},
		{id: 231, name: "Mudgee"},
		{id: 232, name: "Mungindi"},
		{id: 233, name: "Murwillumbah"},
		{id: 234, name: "Narrabri"},
		{id: 235, name: "Nelson Bay"},
		{id: 236, name: "Newcastle"},
		{id: 237, name: "Nowra"},
		{id: 238, name: "Oberon"},
		{id: 239, name: "Orange"},
		{id: 240, name: "Padstow"},
		{id: 241, name: "Parramatta"},
		{id: 242, name: "Penrith"},
		{id: 243, name: "Port Macquarie"},
		{id: 244, name: "Pyrmont"},
		{id: 245, name: "Queanbeyan"},
		{id: 246, name: "Rosebery"},
		{id: 247, name: "Springwood"},
		{id: 248, name: "Srtoud"},
		{id: 249, name: "Sutherland"},
		{id: 250, name: "Sydney"},
		{id: 251, name: "Tamworth"},
		{id: 252, name: "Tingha"},
		{id: 253, name: "Tweed Heads"},
		{id: 254, name: "Ulladulla"},
		{id: 255, name: "Wagga Wagga"},
		{id: 256, name: "Warringa"},
		{id: 257, name: "Wauchope"},
		{id: 258, name: "Wee Jasper"},
		{id: 259, name: "West Wyalong"},
		{id: 260, name: "Windsor"},
		{id: 261, name: "Wollongong"},
		{id: 262, name: "Woronora Heights"},
		{id: 263, name: "Wyong"},
		{id: 264, name: "Yass"},
		{id: 265, name: "Young"},
		{id: 266, name: "Adelaide"},
		{id: 267, name: "Beachport"},
		{id: 268, name: "Brighton"},
		{id: 269, name: "Elizabeth"},
		{id: 270, name: "Loxton"},
		{id: 271, name: "Millicent"},
		{id: 272, name: "Mount Gambier"},
		{id: 273, name: "Murray Bridge"},
		{id: 274, name: "Oodnadatta"},
		{id: 275, name: "Reynella"},
		{id: 276, name: "Whyalla"},
		{id: 277, name: "Woomera"},
		{id: 278, name: "Yorketown"},
		{id: 279, name: "Albany"},
		{id: 280, name: "Armadale"},
		{id: 281, name: "Broome"},
		{id: 282, name: "Bunbury"},
		{id: 283, name: "Carnarvon"},
		{id: 284, name: "Derby"},
		{id: 285, name: "Dongara"},
		{id: 286, name: "Esperance"},
		{id: 287, name: "Exmouth"},
		{id: 288, name: "Fitzroy Crossing"},
		{id: 289, name: "Fremantle"},
		{id: 290, name: "Geraldton"},
		{id: 291, name: "Halls Creek"},
		{id: 292, name: "Harvey"},
		{id: 293, name: "Kalgoorlie"},
		{id: 294, name: "Karratha"},
		{id: 295, name: "Kununurra"},
		{id: 296, name: "Mandurah"},
		{id: 297, name: "Manjimup"},
		{id: 298, name: "Margaret River"},
		{id: 299, name: "Newman"},
		{id: 300, name: "Perth"},
		{id: 301, name: "Port Hedland"},
		{id: 302, name: "Rockingham"},
		{id: 303, name: "Shark Bay"},
		{id: 304, name: "Williamstown"},
		{id: 305, name: "York"},
		{id: 306, name: "Alice Springs"},
		{id: 307, name: "Darwin"},
		{id: 308, name: "Katherine"},
		{id: 309, name: "Tennant Creek"},
		{id: 310, name: "Canberra"},
		{id: 311, name: "AOL"},
		{id: 312, name: "Eisenstadt"},
		{id: 313, name: "Güssing"},
		{id: 314, name: "Neudörfl"},
		{id: 315, name: "Pinkafeld"},
		{id: 316, name: "Stegersbach"},
		{id: 317, name: "Bodensdorf"},
		{id: 318, name: "Döbriach"},
		{id: 319, name: "Feldkirchen"},
		{id: 320, name: "Klagenfurt"},
		{id: 321, name: "Villach"},
		{id: 322, name: "Bad Vöslau"},
		{id: 323, name: "Baden"},
		{id: 324, name: "Ebreichsdorf"},
		{id: 325, name: "Gänserndorf"},
		{id: 326, name: "Grafenbach"},
		{id: 327, name: "Korneuburg"},
		{id: 328, name: "Lilienfeld"},
		{id: 329, name: "Mödling"},
		{id: 330, name: "Neulengbach"},
		{id: 331, name: "Retz"},
		{id: 332, name: "Rosental"},
		{id: 333, name: "Sankt Pölten"},
		{id: 334, name: "Wiener Neustadt"},
		{id: 335, name: "Wieselburg"},
		{id: 336, name: "Zwettl"},
		{id: 337, name: "Bad Hall"},
		{id: 338, name: "Hagenberg"},
		{id: 339, name: "Kremsmünster"},
		{id: 340, name: "Linz"},
		{id: 341, name: "Steyr"},
		{id: 342, name: "Wels"},
		{id: 343, name: "Salzburg"},
		{id: 344, name: "Sankt Johann im Pongau"},
		{id: 345, name: "Tamsweg"},
		{id: 346, name: "Zell am See"},
		{id: 347, name: "Graz"},
		{id: 348, name: "Kindberg"},
		{id: 349, name: "Leoben"},
		{id: 350, name: "Mürzzuschlag"},
		{id: 351, name: "Innsbruck"},
		{id: 352, name: "Jochberg"},
		{id: 353, name: "Kitzbuhel"},
		{id: 354, name: "Reutte"},
		{id: 355, name: "Solden"},
		{id: 356, name: "Wörgl"},
		{id: 357, name: "Zirl"},
		{id: 358, name: "Bregenz"},
		{id: 359, name: "Dornbirn"},
		{id: 360, name: "Götzis"},
		{id: 361, name: "Hohenems"},
		{id: 362, name: "Abtenau"},
		{id: 363, name: "Vienna"},
		{id: 364, name: "Wien"},
		{id: 365, name: "Baku"},
		{id: 366, name: "Freetown"},
		{id: 367, name: "Old Bight"},
		{id: 368, name: "Georgetown"},
		{id: 369, name: "Matthew Town"},
		{id: 370, name: "Abraham's Bay"},
		{id: 371, name: "Nassau"},
		{id: 372, name: "Nassau City"},
		{id: 373, name: "Colonel Hill"},
		{id: 374, name: "Snug Corner"},
		{id: 375, name: "Freeport"},
		{id: 376, name: "Cooper's Town"},
		{id: 377, name: "Behring Point"},
		{id: 378, name: "Marsh Harbour"},
		{id: 379, name: "Sandy Point"},
		{id: 380, name: "Fresh Creek"},
		{id: 381, name: "San Andros"},
		{id: 382, name: "Rock Sound"},
		{id: 383, name: "Cockburn Town"},
		{id: 384, name: "Port Nelson"},
		{id: 385, name: "Al Manamah"},
		{id: 386, name: "Ar Rifa"},
		{id: 387, name: "Awali"},
		{id: 388, name: "Manama"},
		{id: 389, name: "Muharraq"},
		{id: 390, name: "Jasra"},
		{id: 391, name: "Isa Town"},
		{id: 392, name: "Comilla"},
		{id: 393, name: "Dhaka"},
		{id: 394, name: "Khulna"},
		{id: 395, name: "Rajshahi"},
		{id: 396, name: "Saginaw"},
		{id: 397, name: "Christchurch"},
		{id: 398, name: "Bridgetown"},
		{id: 399, name: "Warrens"},
		{id: 400, name: "Speightstown"},
		{id: 401, name: "Brest"},
		{id: 402, name: "Mahilyow"},
		{id: 403, name: "Minsk"},
		{id: 404, name: "Molodechno"},
		{id: 405, name: "Antwerp"},
		{id: 406, name: "Arendonk"},
		{id: 407, name: "Berlaar"},
		{id: 408, name: "Bornem"},
		{id: 409, name: "Geel"},
		{id: 410, name: "Heist-op-den-Berg"},
		{id: 411, name: "Herentals"},
		{id: 412, name: "Lierre"},
		{id: 413, name: "Malines"},
		{id: 414, name: "Mechelen"},
		{id: 415, name: "Mortsel"},
		{id: 416, name: "Puurs"},
		{id: 417, name: "Reet"},
		{id: 418, name: "Turnhout"},
		{id: 419, name: "Westmalle"},
		{id: 420, name: "Binche"},
		{id: 421, name: "Braine-Le-Comte"},
		{id: 422, name: "Charleroi"},
		{id: 423, name: "Frameries"},
		{id: 424, name: "Hennuyeres"},
		{id: 425, name: "La Louvière"},
		{id: 426, name: "Mons"},
		{id: 427, name: "Péruwelz"},
		{id: 428, name: "Soignies"},
		{id: 429, name: "Tournai"},
		{id: 430, name: "Eupen"},
		{id: 431, name: "Huy"},
		{id: 432, name: "Liege"},
		{id: 433, name: "Verviers"},
		{id: 434, name: "Bree"},
		{id: 435, name: "Dilsen"},
		{id: 436, name: "Genk"},
		{id: 437, name: "Hasselt"},
		{id: 438, name: "Kinrooi"},
		{id: 439, name: "Lanaken"},
		{id: 440, name: "Maaseik"},
		{id: 441, name: "Peer"},
		{id: 442, name: "Sint-Truiden"},
		{id: 443, name: "Tongeren"},
		{id: 444, name: "Arlon"},
		{id: 445, name: "Halanzy"},
		{id: 446, name: "Marche-En-Famenne"},
		{id: 447, name: "Ciney"},
		{id: 448, name: "Namur"},
		{id: 449, name: "Rhisnes"},
		{id: 450, name: "Sombreffe"},
		{id: 451, name: "Aalst"},
		{id: 452, name: "Belsele"},
		{id: 453, name: "Dendermonde"},
		{id: 454, name: "Gavere"},
		{id: 455, name: "Gent"},
		{id: 456, name: "Gentbrugge"},
		{id: 457, name: "Holland"},
		{id: 458, name: "Lochristi"},
		{id: 459, name: "Lokeren"},
		{id: 460, name: "Maldegem"},
		{id: 461, name: "Merelbeke"},
		{id: 462, name: "Ninove"},
		{id: 463, name: "Oudenaarde"},
		{id: 464, name: "Sint-Niklaas"},
		{id: 465, name: "Zottegem"},
		{id: 466, name: "Brugge"},
		{id: 467, name: "Diksmuide"},
		{id: 468, name: "Harelbeke"},
		{id: 469, name: "Izegem"},
		{id: 470, name: "Knokke-Heist"},
		{id: 471, name: "Kortrijk"},
		{id: 472, name: "Meulebeke"},
		{id: 473, name: "Middelkerke"},
		{id: 474, name: "Ostend"},
		{id: 475, name: "Pittem"},
		{id: 476, name: "Veurne"},
		{id: 477, name: "Waregem"},
		{id: 478, name: "Brussels"},
		{id: 479, name: "Leuven"},
		{id: 480, name: "Woluwe-Saint-Lambert"},
		{id: 481, name: "Woluwe-Saint-Pierre"},
		{id: 482, name: "Genappe"},
		{id: 483, name: "Grez-Doiceau"},
		{id: 484, name: "Jodoigne"},
		{id: 485, name: "Nivelles"},
		{id: 486, name: "Ottignies"},
		{id: 487, name: "Sint-Margriete-Houtem"},
		{id: 488, name: "Waterloo"},
		{id: 489, name: "Wavre"},
		{id: 490, name: "Aarschot"},
		{id: 491, name: "Boortmeerbeek"},
		{id: 492, name: "Diest"},
		{id: 493, name: "Dilbeek"},
		{id: 494, name: "Grimbergen"},
		{id: 495, name: "Keerbergen"},
		{id: 496, name: "Koningslo"},
		{id: 497, name: "Landen"},
		{id: 498, name: "Overijse"}
	]
}
